before:
  hooks:
    - go mod tidy

builds:
  - id: iam-proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    main: ./cmd/main.go
    binary: iam-proxy
    dir: .

dockers:
  - image_templates:
      - ghcr.io/kotaicode/iam-proxy:{{ .Version }}
      - ghcr.io/kotaicode/iam-proxy:latest
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64,linux/arm64
    extra_files:
      - Dockerfile

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: kotaicode
    name: iam-proxy
  prerelease: auto 